# Generated by Django 5.2.2 on 2025-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("excel", "Excel"),
                    ("csv", "CSV"),
                    ("db", "Database"),
                ],
                max_length=10,
            ),
        ),
    ]
